### ISSUE TITLE
Website isn't available

### ISSUE THREAD

**Issue by llrs** [statdivlab/paramedic#13]
Many thanks for this program. I'm interested in learning more about it (I have some samples with some issues that I think paramedic could help) and wanted to read the documentation before installing the package. The linked https://statdivlab.github.io/paramedic/ website is not available.

I think this is due to not being build by a CI or a github action (as the gh-pages is not available) and there doesn't seem to be any .html files on the main branch. Perhaps it was generated locally with `pkgdown::build_site()` but was not pushed to GitHub?

**Comment by bdwilliamson** [comment]
Thanks for letting us know -- somehow, the gh-pages branch was deactivated. I've just made sure that the website is now available again.

**Comment by llrs** [comment]
Thanks! Now the website displays the README as an html file and the gh-page branch is still not available. Is this the desired webpage?

**Comment by bdwilliamson** [comment]
No, that wasn't the desired webpage! Not sure entirely why the gh-pages branch wasn't being used, but I've created one and have confirmed that the website now looks correct. Thanks again for pointing this out -- I promise that the website used to work with the old workflow.
