### ISSUE TITLE
Errors when running `run_paramedic` on a subset smaller than # of qPCR species

### ISSUE THREAD

**Issue by roey-angel** [statdivlab/paramedic#9]
Running the example with `example_16S_data[, 1:7]` (or anything smaller or equal to `dim(V)[2]`) gives:
`Error in if (sum(names(W_tbl)[-1][1:q_obs] == names(V_tbl)[-1]) != q_obs) { : 
  missing value where TRUE/FALSE needed`

Because `names(W_tbl)[-1][1:q_obs]` appends NA's if `dim(W)[2] <= dim(V)[2]`

**Comment by adw96** [comment]
@roey-angel -- this method was built for the case where you have one dataset with information on *all* taxa (W), and another with information on a subset of taxa (V). Therefore, the column dimension of W should always be at least as large as the column dimension of V.

We are happy to make a produce a more informative error message, but is there something in particular that you're trying to do that this error is blocking you from doing?

**Comment by roey-angel** [comment]
Makes perfect sense, but as it is right now the example in the vignette fails to run because `example_16S_data[, 1:7]` selects the first 6 taxa while `example_qPCR_data` has 7 taxa.
Just wanted to point that out.

**Comment by adw96** [comment]
Ah -- I see what happened here. Late in the game we added tibble attributes to `example_16S_data` and `example_qPCR_data`, and information that was previously in rownames got made into a column.

I will fix right away -- thank you for letting us know.
